// Copyright 2022 Andy Sawyer (nydasco)
// SPDX-License-Identifier: GPL-2.0-or-later

#include "nydasright.h"

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/

